[ja]
  title = "Just Plain Notes"
  LanguageName = "Japanese"
  weight = 1

[en]
  title = "Just Plain Notes"
  LanguageName = "English"
  weight = 2

  # tip: assign the default language the lowest Weight
