name: Container job sample
on:
  push:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:19.1.0-bullseye
    steps:
      - name: show hello
        run: |
          which node
          which yarn
          which git
