name: deploy
on:
  push:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.20.1-bullseye
    steps:
      - name: setup deploy key
        env:
          DEPLOY_SECRETS_KEY: ${{ secrets.DEPLOY_SECRETS_KEY }}
        run: |
          echo "$DEPLOY_SECRETS_KEY" > id_rsa
          chmod 600 id_rsa
      - name: build site
        run: |
          git clone https://github.com/kengo-k/blog-builder.git
          cd blog-builder
          yarn
          yarn build
      - name: deploy site
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ls -la
          echo ">>> clone pages repository..."
          GIT_SSH_COMMAND="ssh -i ~/id_rsa -o StrictHostKeyChecking=no -F /dev/null" git clone git@github.com:kengo-k/pages.git
          echo ">>> copy build result to pages..."
          cp -r blog-builder/docs/.vuepress/dist/* pages/
          ls -la
          cd pages
          git config --global user.email "kurobanekengo@gmail.com"
          git config --global user.name "kengo-k"
          echo ">>> commit new files"
          git add .
          git commit -m"auto commit by github actions"
          echo ">>> push and deploy..."
          GIT_SSH_COMMAND="ssh -i ~/id_rsa -o StrictHostKeyChecking=no -F /dev/null" git push origin main
