name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-gethub-pages:
    runs-on: ubuntu-latest
    container:
      image: node:14.20.1-bullseye
    steps:
      # secretsから読みだした秘密鍵を設置する
      - name: setup deploy key
        env:
          DEPLOY_SECRETS_KEY: ${{ secrets.DEPLOY_SECRETS_KEY }}
        run: |
          echo "$DEPLOY_SECRETS_KEY" > ~/id_rsa
          chmod 600 ~/id_rsa
      # ブログコンテンツのリポジトリをcloneしてビルド
      - name: build site
        run: |
          git clone https://github.com/kengo-k/kengo-k.github.io-builder.git
          cd kengo-k.github.io-builder
          yarn
          yarn build
      # github-pagesにデプロイする
      - name: deploy site
        env:
          GIT_SSH_COMMAND: "ssh -i ~/id_rsa -o StrictHostKeyChecking=no -F /dev/null"
        run: |
          git clone git@github.com:kengo-k/kengo-k.github.io.git
          echo ">>> copy build result to github pages..."
          cp -r kengo-k.github.io-builder/docs/.vuepress/dist/* kengo-k.github.io/
          cd kengo-k.github.io
          git config --global user.email "kurobanekengo@gmail.com"
          git config --global user.name "kengo-k"
          echo ">>> commit new files"
          git add .
          git commit -m"auto commit by github actions"
          echo ">>> push and deploy..."
          git push origin main
