name: deploy
on:
  push:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.20.1-bullseye
    steps:
      - name: build site
        run: |
          git clone https://github.com/kengo-k/blog-builder.git
          cd blog-builder
          yarn
          yarn build
          ls -la
      - name: deploy site
        env:
          DEPLOY_SECRETS_KEY: ${{ secrets.DEPLOY_SECRETS_KEY }}
        run: |
          mkdir .ssh
          cd .ssh
          ls -la
          echo "$DEPLOY_SECRETS_KEY" > id_rsa
          chmod 600 id_rsa
          ls -la
          git clone git@github.com:kengo-k/pages.git
          # git clone https://github.com/kengo-k/pages
          # cp -r blog-builder/docs/.vuepress/dist/* pages/
          # cd pages
          # ls -la

          # git config --global user.email "kurobanekengo@gmail.com"
          # git config --global user.name "kengo-k"
          # git add .
          # git commit -m"auto commit by github actions"
          # git push origin main
