name: deploy
on:
  push:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:14.20.1-bullseye
    steps:
      - name: build site
        run: |
          git clone https://github.com/kengo-k/blog-builder.git
          cd blog-builder
          yarn
          yarn build
          ls -la
      - name: deploy site
        run: |
          git clone https://github.com/kengo-k/pages
          cp -r blog-builder/docs/.vuepress/dist/* pages/
          cd pages
          ls -la
          git status
          echo ${{ secrets.GIT_EMAIL }}
          # git config --global user.email "kurobane"
          # git config --global user.name "Your Name"
          # git add .
          # git commit -m"commit by github actions"
          # git push origin main
