name: deploy
on:
  push:
    branches:
      - release
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          repository: kengo-k/kengo-k.github.io-builder
          path: source

      - name: Install Hugo
        run: |
          HUGO_VERSION="0.100.0"
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
          sudo dpkg -i hugo_extended_${HUGO_VERSION}_Linux-64bit.deb

      - name: Build Site
        run: |
          cd source
          hugo

      - name: Checkout target
        uses: actions/checkout@v2
        with:
          repository: kengo-k/kengo-k.github.io
          token: ${{ secrets.DEPLOY_SECRET_KEY }}
          path: target

      - name: Preserve CNAME
        run: |
          mv target/CNAME CNAME

      - name: Copy artifacts
        run: |
          rm -rf target/*
          cp -r source/public/* target/

      - name: Restore CNAME
        run: |
          mv CNAME target/CNAME

      - name: Deploy
        run:
          cd target
          git config --global user.email "31839234+kengo-k@users.noreply.github.com"
          git config --global user.name "kengo-k"
          git add --all
          git commit --amend -m "deploy automatically by GitHub Actions"
          git push origin main --force
